name: Docker Build And Push to DOCKER HUB

on:
  push:
    branches:
    - main
    paths:
    - 'Dockerfile'
    - '.github/workflows/docker-image.yml'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: |
          VERSION="latest"
          #make a temp dir
          mkdir adjust
          
          #git clone the sample code
          #commenting this code as its not working cause issues. using https://github.com/IBM-Cloud/ruby-sinatra-helloworld.git
          #git clone https://github.com/sawasy/http_server adjust
          git clone https://github.com/IBM-Cloud/ruby-sinatra-helloworld.git adjust
          
          #login to push image to registry
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          
          #build the image locally
          docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/rubyhttps:${VERSION}
          
          #push the image to docker hub
          docker push ${{ secrets.DOCKER_USERNAME }}/rubyhttps:${VERSION}
          
          #remove temp dir
          rm -fr adjust
          
          #remove local docker image
          docker rmi -f ${{ secrets.DOCKER_USERNAME }}/rubyhttps:${VERSION}
